version: "2"

services:
#  db:
#    image: postgres:9.5
#    # restart: always
#    environment:
#      POSTGRES_PASSWORD: root


#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - "8081:8081"

  api:
    #restart: always
    stdin_open: true
    # tty: true
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./bbs_app:/bbs/bbs_app
      - ../www:/www
      # - ./nginx_flask.conf:/etc/nginx/sites-available/nginx_flask.conf
      # - ./gunicorn.conf:/etc/supervisor/conf.d/gunicorn.conf
      # - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    ports:
      - "80:80"
      # 对外端口80, 映射到宿主机的8080