version: "2"

services:
  db:
    image: postgres:alpine
    # restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/postgresql/data/bbs-data
      POSTGRES_DB: bbsdb


#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - "8081:8081"

  api:
    #restart: always
    stdin_open: true
    # tty: true
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ../www:/www
      # - ./nginx_flask.conf:/etc/nginx/sites-available/nginx_flask.conf
      # - ./gunicorn.conf:/etc/supervisor/conf.d/gunicorn.conf
      # - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    ports:
      - "80:80"
      - "2000:2000"
      # 对外端口80, 映射到宿主机的8080