version: "2"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
#      POSTGRES_DB: bbsdb
#    volumes:
#      - /var/lib/postgresql/9.5/main:/db/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8081

  api:
    #restart: always
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./bbs_app:/bbs/bbs_app
      # - ./nginx_flask.conf:/etc/nginx/sites-available/nginx_flask.conf
      # - ./gunicorn.conf:/etc/supervisor/conf.d/gunicorn.conf
      # - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    ports:
      - "8080:80"
      # 对外端口80, 映射到宿主机的8080
    #command: '/bin/bash'
    command: '/usr/bin/supervisord'